spring.application.name=retours
spring.datasource.url=jdbc:mysql://localhost:3306/gestionretours?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
