spring.application.name=retours
spring.datasource.url=jdbc:mysql:///gestionretours?socketFactory=com.google.cloud.sql.mysql.SocketFactory&cloudSqlInstance=gestion-retours-496621:europe-west1:mysql-retours&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
